from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol

from .models import ActiveGame, GameState, LeaderboardEntry, Mode, User


@dataclass(slots=True)
class StoredUserRecord:
    id: str
    username: str
    password_hash: str


@dataclass(slots=True)
class LiveGameRecord:
    id: str
    user_id: str
    username: str
    mode: Mode
    state: GameState
    started_at: int


class Store(Protocol):
    def find_user_by_username(self, username: str) -> StoredUserRecord | None: ...
    def create_user(self, username: str, password: str) -> User: ...
    def authenticate(self, username: str, password: str) -> User | None: ...
    def issue_token(self, user_id: str) -> str: ...
    def revoke_token(self, token: str) -> None: ...
    def user_from_token(self, token: str) -> User | None: ...
    def create_game(self, user: User, mode: Mode) -> str: ...
    def list_active_games(self) -> list[ActiveGame]: ...
    def active_version(self) -> int: ...
    def get_game_state(self, game_id: str) -> GameState | None: ...
    def is_ended_game(self, game_id: str) -> bool: ...
    def update_game_state(self, game_id: str, user: User, state: GameState) -> None: ...
    def complete_game(self, game_id: str, user: User, final_state: GameState) -> None: ...
    def game_version(self, game_id: str) -> int: ...
    def leaderboard_version(self, mode: Mode) -> int: ...
    def list_leaderboard(self, mode: Mode, limit: int = 10) -> list[LeaderboardEntry]: ...
